defaults: &defaults
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") %>
  encoding: utf8
  reconnect: true
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  pool: <%= ENV.fetch("DATABASE_POOL") %>
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *defaults

test:
  <<: *defaults
  database: weather_info_test

production:
  <<: *defaults
  database: weather_info_production
